version: '2.0'
services:
  graphdb:
    image: neo4j:3.1.0
    container_name: scooby-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - /data

  api:
    container_name: scooby-webapi
    build: .
    command: 'npm start'
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - graphdb
    volumes:
      - .:/app
      - /app/node_modules
